server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ml-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/ml/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}
        - id: openapi-docs
          uri: http://localhost:8082
          predicates:
            - Path=/v3/api-docs